name: Proton Service Delete

on:
  schedule:
    - cron: '30 2 * * *'


permissions:
  contents: write
  id-token: write

jobs:
  Proton_Service_Delete:
    name: service_delete
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      id: assume_role
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ap-northeast-1
        role-to-assume: arn:aws:iam::054351901882:role/GithubActionsRole
        role-session-name: TF-Github-Actions
        mask-aws-account-id: 'no'

#     - name: delete service
#       id: delete_service
#       run: >
#         aws lambda invoke
#         --function-name delete-proton-service
#         --payload '{"ignore_service": "[\"inspector*\", \"keep*\"]"}'
#         --cli-binary-format raw-in-base64-out output.json
