name: stage/master push test

on:
  push:
    branches:
      - 'stage/**'

permissions:
  pull-requests: write
  contents: write
  id-token: write

jobs:
  stage_master_push_test:
    name: stage_master_push_test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: test
      run: |
        echo 'stage_master_push_test'