name: test

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write
  id-token: write

jobs:
  service_destroy:
    name: service_destroy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


    - name: Merge master into stage/master
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config user.name ryusuketesaki
        git config user.email ryusuke.tesaki@i-plug.co.jp
        git fetch
        git checkout stage/main
        git merge --allow-unrelated-histories -Xtheirs main --no-edit
        git commit --allow-empty -m "test"
        git push origin stage/main
