name: test

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write
  id-token: write

jobs:
  service_destroy:
    name: service_destroy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge master into stage/master
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git fetch
        git checkout stage/main
        git merge --allow-unrelated-histories -Xtheirs main --no-edit
        git commit --allow-empty -m "test"
        git push origin stage/main
