name: on_concurrency_test_11

concurrency:
  concurrency_group_1

on:
  workflow_dispatch:

jobs:
  concurrency_workflow:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: sleep 30

